site_name: Diverse Epigenetics Epidemiology 
theme:
  name: material
  features:
    - navigation.tabs # Add horizontal navigation tabs
    - navigation.tabs.sticky # Keep the header menu visible
    - navigation.instant # Simulate an SPA (no page flicker / reload)
  logo: assets/logo_banner.png # Add our logo to the header bar
  favicon: images/logo_banner.png
  palette:
    primary: white #changes header bar and accent colours to teal see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    accent: blue
  custom_dir: custom_theme/
extra:
  generator: false #removes "made with Material for mkdocs" from footer
  #social: #add socials to footer
  #  - icon: fontawesome/brands/twitter 
  #    link: twitter.com
copyright: Copyright &copy; 2023 DEEP

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 0

nav:
  - Home:
    - index.md #This is the first page you land on when you visit "Home"
  - Research: #This is a tab on my page as I'm using the tabs feature for navigation.
    - Research.md #This is the first page you land on when you visit "Setup"
  - Our Network: 
    - Our_Network.md #This is a file under the "Users & Permissions" drop-down.
  - 'Strategy':
    - Strategy.md #This is the page you land on when you visit "Strategy"
  - News:
    - News.md #This is the first page you land on when you visit "Home"
  - Publications:
    - Publications.md #This is the first page you land on when you visit "Home"
  - Contact:
    - Contact.md #This is the first page you land on when you visit "Home"
